"""rename department

Revision ID: 946c854f8293
Revises: a47dddec17fc
Create Date: 2025-09-09 13:31:56.139205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946c854f8293'
down_revision = 'a47dddec17fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
